[package]
name = "smoldot-light"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Browser bindings to a light client for Substrate-based blockchains"
repository = "https://github.com/paritytech/smoldot"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2021"

[[example]]
name = "basic"
required-features = ["std"]

[dependencies]
blake2-rfc = { version = "0.2.18", default-features = false }
derive_more = "0.99.17"
either = { version = "1.8.0", default-features = false }
event-listener = { version = "2.5.3" }
fnv = { version = "1.0.7", default-features = false }
futures = "0.3.25"
hashbrown = { version = "0.12.3", default-features = false }
hex = { version = "0.4.3", default-features = false }
itertools = "0.10.5"
log = { version = "0.4.17", default-features = false }
lru = { version = "0.8.1", default-features = false }  # TODO: there's no way to use a custom hasher; remove this dependency
rand = "0.8.5"
serde = { version = "1.0.145", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.87"
slab = { version = "0.4.7", default-features = false }
smoldot = { version = "0.4.0", path = "../..", default-features = false }

# `std` feature
# Add here the crates that cannot function without the help of the operating system or environment.
async-std = { version = "1.12.0", optional = true }
parking_lot = { version = "0.12.1", optional = true }

[features]
default = ["std"]
std = ["async-std", "parking_lot", "smoldot/std"]

[dev-dependencies]
env_logger = "0.9.1"
